//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PloobsEngine {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResourcesPC {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourcesPC() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PloobsEngine.ResourcesPC", typeof(ResourcesPC).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static byte[] AllBuffer {
            get {
                object obj = ResourceManager.GetObject("AllBuffer", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] AnimatedBillboard {
            get {
                object obj = ResourceManager.GetObject("AnimatedBillboard", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] AntiAliasing {
            get {
                object obj = ResourceManager.GetObject("AntiAliasing", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] AntiAliasingtabulastalker {
            get {
                object obj = ResourceManager.GetObject("AntiAliasingtabulastalker", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] BlackWhite {
            get {
                object obj = ResourceManager.GetObject("BlackWhite", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] BlinkGBuffer {
            get {
                object obj = ResourceManager.GetObject("BlinkGBuffer", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] block {
            get {
                object obj = ResourceManager.GetObject("block", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] blur {
            get {
                object obj = ResourceManager.GetObject("blur", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] BumpGBuffer {
            get {
                object obj = ResourceManager.GetObject("BumpGBuffer", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] ByPassEffect {
            get {
                object obj = ResourceManager.GetObject("ByPassEffect", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] checker {
            get {
                object obj = ResourceManager.GetObject("checker", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] cilBilboard {
            get {
                object obj = ResourceManager.GetObject("cilBilboard", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] cilBilboardForward {
            get {
                object obj = ResourceManager.GetObject("cilBilboardForward", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] ClearGBuffer {
            get {
                object obj = ResourceManager.GetObject("ClearGBuffer", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] clippingPlane {
            get {
                object obj = ResourceManager.GetObject("clippingPlane", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] color_map {
            get {
                object obj = ResourceManager.GetObject("color_map", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] colorCorrection {
            get {
                object obj = ResourceManager.GetObject("colorCorrection", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Combine {
            get {
                object obj = ResourceManager.GetObject("Combine", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] CombineFinal {
            get {
                object obj = ResourceManager.GetObject("CombineFinal", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] ConsoleFont {
            get {
                object obj = ResourceManager.GetObject("ConsoleFont", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] contrast {
            get {
                object obj = ResourceManager.GetObject("contrast", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] CopyToScreen {
            get {
                object obj = ResourceManager.GetObject("CopyToScreen", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] CuingDepth {
            get {
                object obj = ResourceManager.GetObject("CuingDepth", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] DeferredAA {
            get {
                object obj = ResourceManager.GetObject("DeferredAA", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Depth {
            get {
                object obj = ResourceManager.GetObject("Depth", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] depth1 {
            get {
                object obj = ResourceManager.GetObject("depth1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] DirectionalLight {
            get {
                object obj = ResourceManager.GetObject("DirectionalLight", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] dome {
            get {
                object obj = ResourceManager.GetObject("dome", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] DownScaling {
            get {
                object obj = ResourceManager.GetObject("DownScaling", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Dsphere {
            get {
                object obj = ResourceManager.GetObject("Dsphere", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Embossed {
            get {
                object obj = ResourceManager.GetObject("Embossed", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] EMSHADER {
            get {
                object obj = ResourceManager.GetObject("EMSHADER", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] explosion {
            get {
                object obj = ResourceManager.GetObject("explosion", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] fire {
            get {
                object obj = ResourceManager.GetObject("fire", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] flare {
            get {
                object obj = ResourceManager.GetObject("flare", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Fog {
            get {
                object obj = ResourceManager.GetObject("Fog", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] FULLGPUBlur {
            get {
                object obj = ResourceManager.GetObject("FULLGPUBlur", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] gamma {
            get {
                object obj = ResourceManager.GetObject("gamma", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] GaussianBlur {
            get {
                object obj = ResourceManager.GetObject("GaussianBlur", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] gblur {
            get {
                object obj = ResourceManager.GetObject("gblur", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] gcpublur {
            get {
                object obj = ResourceManager.GetObject("gcpublur", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] glow {
            get {
                object obj = ResourceManager.GetObject("glow", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] glowPost {
            get {
                object obj = ResourceManager.GetObject("glowPost", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] GrassBillboard {
            get {
                object obj = ResourceManager.GetObject("GrassBillboard", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Heat {
            get {
                object obj = ResourceManager.GetObject("Heat", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] HSV {
            get {
                object obj = ResourceManager.GetObject("HSV", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] InstancedBilboard {
            get {
                object obj = ResourceManager.GetObject("InstancedBilboard", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] InstanceRenderGBuffer {
            get {
                object obj = ResourceManager.GetObject("InstanceRenderGBuffer", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Inverse {
            get {
                object obj = ResourceManager.GetObject("Inverse", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] LineDetection {
            get {
                object obj = ResourceManager.GetObject("LineDetection", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Luminance {
            get {
                object obj = ResourceManager.GetObject("Luminance", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] MotionBlur {
            get {
                object obj = ResourceManager.GetObject("MotionBlur", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Night {
            get {
                object obj = ResourceManager.GetObject("Night", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] noise {
            get {
                object obj = ResourceManager.GetObject("noise", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] noise_tex6 {
            get {
                object obj = ResourceManager.GetObject("noise_tex6", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] normal {
            get {
                object obj = ResourceManager.GetObject("normal", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] opacity {
            get {
                object obj = ResourceManager.GetObject("opacity", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] ParticleEffect {
            get {
                object obj = ResourceManager.GetObject("ParticleEffect", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] particles {
            get {
                object obj = ResourceManager.GetObject("particles", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] PlanarOriented {
            get {
                object obj = ResourceManager.GetObject("PlanarOriented", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] PointLight {
            get {
                object obj = ResourceManager.GetObject("PointLight", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Posterize {
            get {
                object obj = ResourceManager.GetObject("Posterize", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] RadialBlur {
            get {
                object obj = ResourceManager.GetObject("RadialBlur", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] random {
            get {
                object obj = ResourceManager.GetObject("random", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] RANDOMNORMAL {
            get {
                object obj = ResourceManager.GetObject("RANDOMNORMAL", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] reductionEffect {
            get {
                object obj = ResourceManager.GetObject("reductionEffect", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Reflection {
            get {
                object obj = ResourceManager.GetObject("Reflection", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] RenderGBuffer {
            get {
                object obj = ResourceManager.GetObject("RenderGBuffer", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] RenderGlowBuffer {
            get {
                object obj = ResourceManager.GetObject("RenderGlowBuffer", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] resolveShadowsEffect {
            get {
                object obj = ResourceManager.GetObject("resolveShadowsEffect", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] RestoreDepth {
            get {
                object obj = ResourceManager.GetObject("RestoreDepth", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Ripple {
            get {
                object obj = ResourceManager.GetObject("Ripple", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] RoundLine {
            get {
                object obj = ResourceManager.GetObject("RoundLine", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Saturate {
            get {
                object obj = ResourceManager.GetObject("Saturate", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] saturation {
            get {
                object obj = ResourceManager.GetObject("saturation", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Scatter {
            get {
                object obj = ResourceManager.GetObject("Scatter", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] ShadowDepth {
            get {
                object obj = ResourceManager.GetObject("ShadowDepth", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] ShadowDirectional {
            get {
                object obj = ResourceManager.GetObject("ShadowDirectional", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] ShadowDirectionalCascade {
            get {
                object obj = ResourceManager.GetObject("ShadowDirectionalCascade", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] ShadowMap {
            get {
                object obj = ResourceManager.GetObject("ShadowMap", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] ShadowMap1 {
            get {
                object obj = ResourceManager.GetObject("ShadowMap1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] ShadowPoint {
            get {
                object obj = ResourceManager.GetObject("ShadowPoint", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] ShadowSpot {
            get {
                object obj = ResourceManager.GetObject("ShadowSpot", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] SimpleAlphaDraw {
            get {
                object obj = ResourceManager.GetObject("SimpleAlphaDraw", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] skybox {
            get {
                object obj = ResourceManager.GetObject("skybox", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] smoke {
            get {
                object obj = ResourceManager.GetObject("smoke", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] SpecularBumpBuffer {
            get {
                object obj = ResourceManager.GetObject("SpecularBumpBuffer", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] SpecularMapBuffer {
            get {
                object obj = ResourceManager.GetObject("SpecularMapBuffer", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] sphere {
            get {
                object obj = ResourceManager.GetObject("sphere", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] SphericalBillboard {
            get {
                object obj = ResourceManager.GetObject("SphericalBillboard", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] SpotLight {
            get {
                object obj = ResourceManager.GetObject("SpotLight", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] ssaoblur {
            get {
                object obj = ResourceManager.GetObject("ssaoblur", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] SSAOBlur1 {
            get {
                object obj = ResourceManager.GetObject("SSAOBlur1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] SSAOBlur2 {
            get {
                object obj = ResourceManager.GetObject("SSAOBlur2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] ssaofinal {
            get {
                object obj = ResourceManager.GetObject("ssaofinal", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] SSAOPOST {
            get {
                object obj = ResourceManager.GetObject("SSAOPOST", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Sun {
            get {
                object obj = ResourceManager.GetObject("Sun", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Sunset {
            get {
                object obj = ResourceManager.GetObject("Sunset", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Terrain {
            get {
                object obj = ResourceManager.GetObject("Terrain", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] terrainShader {
            get {
                object obj = ResourceManager.GetObject("terrainShader", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] teste {
            get {
                object obj = ResourceManager.GetObject("teste", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Threshold {
            get {
                object obj = ResourceManager.GetObject("Threshold", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Tilling {
            get {
                object obj = ResourceManager.GetObject("Tilling", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] ToBlack {
            get {
                object obj = ResourceManager.GetObject("ToBlack", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] ToneHdr {
            get {
                object obj = ResourceManager.GetObject("ToneHdr", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] ToneMapping {
            get {
                object obj = ResourceManager.GetObject("ToneMapping", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Toon {
            get {
                object obj = ResourceManager.GetObject("Toon", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] toon1 {
            get {
                object obj = ResourceManager.GetObject("toon1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] TransparentEffect {
            get {
                object obj = ResourceManager.GetObject("TransparentEffect", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Vidro {
            get {
                object obj = ResourceManager.GetObject("Vidro", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Water {
            get {
                object obj = ResourceManager.GetObject("Water", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] WaterComplete {
            get {
                object obj = ResourceManager.GetObject("WaterComplete", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] wave0 {
            get {
                object obj = ResourceManager.GetObject("wave0", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] wave1 {
            get {
                object obj = ResourceManager.GetObject("wave1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] waves2 {
            get {
                object obj = ResourceManager.GetObject("waves2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] white {
            get {
                object obj = ResourceManager.GetObject("white", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] wiggle {
            get {
                object obj = ResourceManager.GetObject("wiggle", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
